### ISSUE TITLE
OAuth authorization error (invalid_request): A required parameter "client_id" is missing.

### ISSUE THREAD

**Issue by Ayoola** [dart-lang/oauth2#93]
I'm trying implement Linkedin oauth2 in Flutter using Webview. 

Everything seems to be set up correctly and I've managed to get the responseUrl. 

However, when I call the grant.handleAuthorizationResponse(responseUrl.queryParameters) function, I get a Unhandled Exception: OAuth authorization error (invalid_request): A required parameter "client_id" is missing.

Stack Trace:

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: OAuth authorization error (invalid_request): A required parameter "client_id" is missing.
#0      _handleErrorResponse (package:oauth2/src/handle_access_token_response.dart:143:3)
#1      handleAccessTokenResponse (package:oauth2/src/handle_access_token_response.dart:41:7)
#2      AuthorizationCodeGrant._handleAuthorizationCode (package:oauth2/src/authorization_code_grant.dart:322:23)
<asynchronous suspension>
#3      AuthorizationCodeGrant.handleAuthorizationResponse (package:oauth2/src/authorization_code_grant.dart:267:18)
#4      AuthorizationHelper.createClient (package:influencr/authorization_helper.dart:34:36)
#5      _AuthWebviewState.build.<anonymous closure> (package:influencr/screens/auth_webview.dart:42:20)
#6      _PlatformCallbacksHandler.onNavigationRequest (package:webview_flutter/webview_flutter.dart:537:41)
#7      MethodChannelWebViewPlatform._onMethodCall (package:webview_flutter/src/webview_method_channel.dart:36:48)
#8      M<…>
```

**Comment by bryantgtx** [comment]
I just ran into this - you may need to set basicAuth to 'false' in the AuthorizationCodeGrant constructor.

```
    var grant = oauth2.AuthorizationCodeGrant(
      clientId,
      _authorizationEndpoint,
      _tokenEndpoint,
      secret: widget.clientSecret,
      httpClient: _JsonAcceptingHttpClient(),
      basicAuth: false,
    );
```
The code defaults to basicAuth being true, which is taking your clientSecret and passing it in the header as a bearer token. (authorization_code_grant.dart:310)
